#1 style & other
DenisLukashov/LP15-awesome-project pull request #30
Opened 2020-01-25 18:13 UTC by DenisLukashov

2020-01-26 21:42 UTC, Roxe322 commented on awesomeapp/statistics/models.py
> +            story_and_images = {'story': 'нет данных'}
Не надо делать строку нет данных, отправляйте None

2020-01-26 21:42 UTC, Roxe322 commented on awesomeapp/statistics/models.py
> +        try:
Избавьтесь от всех try и сделайте на ифах. Это дешевле и симпатичнее, чем обработка исключений

2020-01-26 21:42 UTC, Roxe322 commented on awesomeapp/statistics/models.py
> +                ).one().story.text
Почему one, а не first?

2020-01-26 21:42 UTC, Roxe322 commented on awesomeapp/statistics/templates/statistics/carousel.html
> +                alt="Фотографий нет"
Почему в alt "Фотографий нет"?

2020-01-26 21:42 UTC, Roxe322 commented on awesomeapp/statistics/views.py
> +        if start_date > end_date:
Мне кажется, свапать тут - плохая идея. Нужно валидировать, чтобы start_date не был больше end_date и показывать ошибку, если так

2020-01-26 21:42 UTC, Roxe322 commented on awesomeapp/statistics/utils.py
> +    return data
сворачивается в тернарный оператор. И название у функции говно. Что за is_null? функция с таким названием должна возвращать тру или фолс

2020-01-26 21:42 UTC, Roxe322 commented on awesomeapp/templates/menu.html
> +    <a class="navbar-brand" href="/">AwesomeStats</a>
Здесь тоже должен быть url_for

2020-01-26 21:46 UTC, DenisLukashov commented on awesomeapp/statistics/views.py
> +        if start_date > end_date:
зачем валидировать и тратить время пользователя, когда можно показать, то что он хотел даже если он рукожоп

2020-01-27 10:41 UTC, DenisLukashov commented on awesomeapp/statistics/models.py
> +            story_and_images = {'story': 'нет данных'}
+

2020-01-27 11:04 UTC, DenisLukashov commented on awesomeapp/statistics/models.py
> +                ).one().story.text
+

2020-01-27 11:04 UTC, DenisLukashov commented on awesomeapp/statistics/utils.py
> +    return data
+

2020-01-27 11:04 UTC, DenisLukashov commented on awesomeapp/templates/menu.html
> +    <a class="navbar-brand" href="/">AwesomeStats</a>
+

2020-01-27 11:04 UTC, DenisLukashov commented on awesomeapp/statistics/views.py
> +        if start_date > end_date:
-

2020-01-27 11:11 UTC, DenisLukashov commented on awesomeapp/statistics/templates/statistics/carousel.html
> +                alt="Фотографий нет"
+

2020-01-27 11:41 UTC, DenisLukashov commented on awesomeapp/statistics/models.py
> +        try:
+

2020-01-27 11:46 UTC, Roxe322 commented on awesomeapp/statistics/templates/statistics/carousel.html
> +                        alt="фото с тренеровки"
тренировка

2020-01-27 11:46 UTC, Roxe322 commented on awesomeapp/statistics/templates/statistics/stats_view.html
> +            {% if story_and_images.story != None %}
https://jinja.palletsprojects.com/en/2.10.x/templates/#none . Не надо сравнивать с None через =

2020-01-27 11:46 UTC, Roxe322 commented on awesomeapp/statistics/views.py
> +        if start_date > end_date:
Он этого не хотел. Не нужно додумывать за пользователя. Это как если ты регистриуешь почту, твой мейл занят и тебе АВТОМАТОМ хуячит рандомные цифры в конец

2020-01-27 11:46 UTC, Roxe322 commented on awesomeapp/statistics/utils.py
> +def convert_null_to_int(data):
null?

2020-01-27 12:02 UTC, DenisLukashov commented on awesomeapp/statistics/templates/statistics/carousel.html
> +                        alt="фото с тренеровки"
+

2020-01-27 12:10 UTC, DenisLukashov commented on awesomeapp/statistics/utils.py
> +def convert_null_to_int(data):
+

2020-01-27 12:26 UTC, DenisLukashov commented on awesomeapp/statistics/templates/statistics/stats_view.html
> +            {% if story_and_images.story != None %}
+

2020-01-27 12:44 UTC, DenisLukashov commented on awesomeapp/statistics/views.py
> +        if start_date > end_date:
+

2020-01-28 13:20 UTC, Roxe322 requested changes

2020-01-28 13:20 UTC, Roxe322 commented on awesomeapp/statistics/forms.py
> +        rv = FlaskForm.validate(self)
что за rv? И это делается с помощью super()

2020-01-28 13:20 UTC, Roxe322 commented on awesomeapp/statistics/templates/statistics/stats_view.html
> +                <p class="small_text">О тренеровке:
-_-

2020-01-28 13:27 UTC, DenisLukashov commented on awesomeapp/statistics/templates/statistics/stats_view.html
> +                <p class="small_text">О тренеровке:
Хаз

2020-01-28 14:06 UTC, merged